// Generated by Cypress Author on 2026-06-23.
import { EmojiCard } from './EmojiCard';
import { CartProvider, useCart } from '../context/CartContext';
import { Emoji } from '../types';

// Small consumer used only in tests to surface the cart state to the DOM,
// so we can assert the result of the "Add to Cart" interaction.
function CartViewer() {
  const { cart } = useCart();
  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
  return <div data-testid="cart-count">{totalItems}</div>;
}

describe('<EmojiCard />', () => {
  const emoji: Emoji = {
    id: '1',
    symbol: '🚀',
    name: 'Rocket',
    description: 'Blast off to the moon',
    price: 4.99,
    category: 'objects',
  };

  let onClick: Cypress.Agent<sinon.SinonStub>;

  beforeEach(() => {
    // Arrange: EmojiCard relies on the cart context, so wrap it in CartProvider.
    onClick = cy.stub().as('onClick');
    cy.mount(
      <CartProvider>
        <EmojiCard emoji={emoji} onClick={onClick} />
        <CartViewer />
      </CartProvider>
    );
  });

  it('renders the emoji details and price', () => {
    // Assert: the user sees the emoji card content
    cy.get('[data-testid="emoji-card"]').within(() => {
      cy.contains(emoji.symbol).should('be.visible');
      cy.contains('h3', emoji.name).should('be.visible');
      cy.contains(emoji.description).should('be.visible');
      cy.contains('$4.99').should('be.visible');
      cy.contains('button', 'Add to Cart').should('be.visible');
    });
  });

  it('clicking the card body → invokes the onClick callback', () => {
    // Act
    cy.contains(emoji.name).click();

    // Assert
    cy.get('@onClick').should('have.been.calledOnce');
  });

  it('clicking "Add to Cart" → adds the emoji to the cart without triggering onClick', () => {
    // Assert: cart starts empty
    cy.get('[data-testid="cart-count"]').should('have.text', '0');

    // Act
    cy.contains('button', 'Add to Cart').click();

    // Assert: the emoji is added and the card onClick did not fire (stopPropagation)
    cy.get('[data-testid="cart-count"]').should('have.text', '1');
    cy.get('@onClick').should('not.have.been.called');
  });

  it('clicking "Add to Cart" twice → increases the quantity of the same emoji', () => {
    // Act
    cy.contains('button', 'Add to Cart').click().click();

    // Assert: same emoji accumulates quantity rather than duplicating
    cy.get('[data-testid="cart-count"]').should('have.text', '2');
  });
});
