// Generated by Cypress Author on 2026-06-23.
import { ThankYouPage } from './ThankYouPage';

describe('<ThankYouPage />', () => {
  const orderNumber = 'ORD-12345';
  let onBackToStore: Cypress.Agent<sinon.SinonStub>;

  beforeEach(() => {
    // Arrange: mount with the required props, spying on the callback
    onBackToStore = cy.stub().as('onBackToStore');
    cy.mount(
      <ThankYouPage orderNumber={orderNumber} onBackToStore={onBackToStore} />
    );
  });

  it('shows the confirmation message and order number', () => {
    // Assert: the user sees the thank-you content
    cy.contains('h1', 'Thank You for Your Purchase!').should('be.visible');
    cy.contains(
      "Your order has been successfully placed. We've sent a confirmation email with your order details."
    ).should('be.visible');
    cy.contains('Order Number').should('be.visible');
    cy.contains(orderNumber).should('be.visible');
  });

  it('clicking "Back to Store" → invokes the onBackToStore callback', () => {
    // Act
    cy.contains('button', 'Back to Store').click();

    // Assert
    cy.get('@onBackToStore').should('have.been.calledOnce');
  });
});
