// Generated by Cypress Author - 2026-06-22
describe('Customer Support Center', () => {
  it('fill in mandatory fields and submit → success message is displayed', () => {
    // Arrange
    const firstName = 'John'
    const lastName = 'Doe'
    const email = 'john.doe@example.com'
    const helpText = 'I need help with my order.'

    // Act
    cy.visit('/index.html')
    cy.get('#firstName').type(firstName)
    cy.get('#lastName').type(lastName)
    cy.get('#email').type(email)
    cy.get('#open-text-area').type(helpText)
    cy.contains('button', 'Send').click()

    // Assert
    cy.get('span.success')
      .should('be.visible')
      .and('contain.text', 'Message successfully sent.')
  })
})
