// Generated by Cypress Author on 2026-06-23.
// API tests for the EngageSphere REST API (GET /customers).

describe('EngageSphere API - GET /customers', () => {
  it('gets customers with the default parameters → returns 200 and the expected body structure', () => {
    // Act
    cy.request('/customers').then(({ status, body }) => {
      // Assert
      expect(status).to.equal(200)
      expect(body.customers).to.be.an('array')
      expect(body.pageInfo).to.have.all.keys('currentPage', 'totalPages', 'totalCustomers')
    })
  })

  it('gets a specific page → returns 200 and the expected body structure', () => {
    // Act
    cy.request('/customers?page=2').then(({ status, body }) => {
      // Assert
      expect(status).to.equal(200)
      expect(body.customers).to.be.an('array')
      expect(body.pageInfo).to.have.all.keys('currentPage', 'totalPages', 'totalCustomers')
    })
  })

  it('gets customers with a custom limit → returns 200 and at most the requested number of customers', () => {
    // Act
    cy.request('/customers?limit=2').then(({ status, body }) => {
      // Assert
      expect(status).to.equal(200)
      expect(body.customers).to.be.an('array')
      expect(body.customers).to.have.length.of.at.most(2)
      expect(body.pageInfo).to.have.all.keys('currentPage', 'totalPages', 'totalCustomers')
    })
  })

  it('filters by size → returns 200 and only Enterprise customers', () => {
    // Act
    cy.request('/customers?size=Enterprise').then(({ status, body }) => {
      // Assert
      expect(status).to.equal(200)
      expect(body.customers).to.be.an('array')
      body.customers.forEach((customer) => {
        expect(customer.size).to.equal('Enterprise')
      })
      expect(body.pageInfo).to.have.all.keys('currentPage', 'totalPages', 'totalCustomers')
    })
  })

  it('filters by a size that contains spaces → returns 200 and only Large Enterprise customers', () => {
    // Act
    // The space in "Large Enterprise" is URL-encoded as %20.
    cy.request('/customers?size=Large%20Enterprise').then(({ status, body }) => {
      // Assert
      expect(status).to.equal(200)
      expect(body.customers).to.be.an('array')
      body.customers.forEach((customer) => {
        expect(customer.size).to.equal('Large Enterprise')
      })
      expect(body.pageInfo).to.have.all.keys('currentPage', 'totalPages', 'totalCustomers')
    })
  })

  it('filters by industry → returns 200 and only Retail customers', () => {
    // Act
    cy.request('/customers?industry=Retail').then(({ status, body }) => {
      // Assert
      expect(status).to.equal(200)
      expect(body.customers).to.be.an('array')
      body.customers.forEach((customer) => {
        expect(customer.industry).to.equal('Retail')
      })
      expect(body.pageInfo).to.have.all.keys('currentPage', 'totalPages', 'totalCustomers')
    })
  })

  it('filters by size Small on page 1 → returns only Small customers and numeric pageInfo values', () => {
    // Act
    // Page 1 guarantees at least one customer for the requested size.
    cy.request('/customers?page=1&size=Small').then(({ status, body }) => {
      // Assert
      expect(status).to.equal(200)
      body.customers.forEach((customer) => {
        expect(customer.size).to.equal('Small')
      })
      expect(body.pageInfo.currentPage).to.be.a('number')
      expect(body.pageInfo.totalPages).to.be.a('number')
      expect(body.pageInfo.totalCustomers).to.be.a('number')
    })
  })

  it('filters by industry HR on page 1 → returns only HR customers and numeric pageInfo values', () => {
    // Act
    // Page 1 guarantees at least one customer for the requested industry.
    cy.request('/customers?page=1&industry=HR').then(({ status, body }) => {
      // Assert
      expect(status).to.equal(200)
      body.customers.forEach((customer) => {
        expect(customer.industry).to.equal('HR')
      })
      expect(body.pageInfo.currentPage).to.be.a('number')
      expect(body.pageInfo.totalPages).to.be.a('number')
      expect(body.pageInfo.totalCustomers).to.be.a('number')
    })
  })

  it('rejects page zero → returns 400', () => {
    // Act
    cy.request({ url: '/customers?page=0', failOnStatusCode: false }).then(({ status }) => {
      // Assert
      expect(status).to.equal(400)
    })
  })

  it('rejects a negative limit → returns 400', () => {
    // Act
    cy.request({ url: '/customers?limit=-1', failOnStatusCode: false }).then(({ status }) => {
      // Assert
      expect(status).to.equal(400)
    })
  })

  it('rejects an unsupported size → returns 400', () => {
    // Act
    cy.request({ url: '/customers?size=Tiny', failOnStatusCode: false }).then(({ status }) => {
      // Assert
      expect(status).to.equal(400)
    })
  })

  it('rejects an unsupported industry → returns 400', () => {
    // Act
    cy.request({ url: '/customers?industry=Education', failOnStatusCode: false }).then(({ status }) => {
      // Assert
      expect(status).to.equal(400)
    })
  })
})
